---
title: "Comment Mining Write Up - I"
author: "Anders Swanson"
output:
  html_document:
    depth: 3
    toc: yes
    theme: spacelab
bibliography: library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Background


I just finished four years teaching math at Xiamen International School: a private, International Baccalaureate K12 school teaching middle and high school in Fujian Province, China.

In addition to reporting achievement levels according to criterion-based rubrics for each student, we also had to write three sentences about how the student and their progress in class.

For a variety of reasons I'll mention below, I struggled to get my comments finished. That combined with the fact that [I overthink things](https://pics.onsizzle.com/hmmm-yeah-i-think-so-did-i-this-is-helping-2789638.png) led me down a rabbit hole of trying to eke out the value of comments.

So here goes nothing.


### Research Question

#### Ideal question
> What effect do teacher-written trimester comments have on future student performance?

#### Realistic question
> How does the language used to describe students in trimester one comments vary depending on level of improvement in trimester two?

***
### Purpose  

<br><br>

##### 1. Seek out what an "effective" comment is. 


The difficulty with comments is that it takes a long time to write these comments and by the time there are in parents' hands it may be too late for it to be considered effective feedback. Additionally, a minority of our parents speak English as a first language. These reasons and others made diving into the value of a comment very alluring to me.

 > The problem with our report cards is that grades and comments are always encoded and not standard-referenced ... The report card should, above all else, be user-friendly: Parents [and students] must be able to easily understand the information it contains.-- *Grant Wiggins* [@Wiggins1994]

##### 2. Enhance Creativity of Teachers  
I love the conversations I've had in workshops concerning "data-driven" teaching and learning as well as the idea of action research. However, the majority of tools for educational data analysis (MAP, SAT, Atlas Rubicon) tend not to give actionable suggestions to teachers as to how to improve their practice. I want to use real data to give practice-based recommendations for helping students learn and improve.

##### 3. Learn R

I started this project having only competed the first few courses of the Johns Hopkins Data Science specialization series on Coursera. I knew basics of R but I hoped to become more fluent as I went. I've definitely learned a lot and moved beyond the syntax to understand more about R, especially packages like tm, dplyr, knitr, and ggplot2.


***
### Principles

<br><br>

##### 1. Share results with community  

This article is a start. Also my full github repository can be found [here](https://github.com/swanderz/xis_mining)

##### 2. Produce reliable, readable, commented code  

I hope I've done that! But I certainly can't claim any efficiency.

##### 3. Strive for "good enough"  
I've started and stopped this project three times now over the course of a year. I've branched off and explored MANY different aspects of this dataset but in the end the story I'm telling now is the one I set out at the beginning to answer.


***


[^1]: asdfasdfasdfasdf
[^2]: The average growth should be the difference between the Criteria Means of trimester one and two but the average growth excludes mid-year students who: 1) typically don't do well in their 1st trimester of MYP and 2) are not represented in the T1-T2 growth statistic.
[^3]: A lot of assumptions going on here....
[^4]: Name removed for privacy

